#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>

#define BINCONV_MAJOR         0
#define BINCONV_MINOR         1
#define BINCONV_PATCH         0

#define BINCONV_LANGS_C       0x01
#define BINCONV_LANGS_RUST    0x02
#define BINCONV_LANGS_NASM    0x03

#define BINCONV_FLAGS_VERBOSE 0x01

int main(int argc, char * argv[]) {
    // Copyright
    printf("binconv %d.%d.%d - Copyright (c) 2023 Felipe C.\n", BINCONV_MAJOR, BINCONV_MINOR, BINCONV_PATCH);
    
    // Gets arguments
    if (argc > 1) {
        // Settings
        char * input        = NULL;
        char * output       = "out.c";
        unsigned char lang  = BINCONV_LANGS_C;
        unsigned char flags = 0;
        
        // Help dialog
        if (argc <= 2) {
            if (!strcmp(argv[1], "--help")) {
                printf("Converts binaries to arrays in multiple programming languages (currently C, C++ and Rust).\n");
                printf("Usage: binconv [command] or <flags>\n\n");
                printf("Commands: \n");
                printf(" --help: shows this\n");
                printf("Flags: \n");
                printf(" -f: programming language .... c or rust\n");
                printf(" -i: file input .............. no specification\n");
                printf(" -o: file output ............. no specification\n");
                printf(" -v: verbose ................. no specification\n");
                return 0;
            } else if (!strcmp(argv[1], "--version")) {
                return 0;
            } else {
                fprintf(stderr, "binconv: error: unknown command \"%s\"", argv[1]);
                return -1;
            }
        }
        
        // Arguments
        ++argv;    
        while (* argv) {
            if (!strcmp(* argv, "-fc")) {
                lang = BINCONV_LANGS_C;
            } else if (!strcmp(* argv, "-frust")) {
                lang   = BINCONV_LANGS_RUST;
                output = "out.rs";
            } else if (!strcmp(* argv, "-v")) {
                flags |= BINCONV_FLAGS_VERBOSE;
            } else if (!strcmp(* argv, "-i")) {
                input = * ++argv;
            } else if (!strcmp(* argv, "-o")) {
                output = * ++argv;
            } else {
                fprintf(stderr, "binconv: error: unknown flag \"%s\"", * argv);
                return -1;
            }
            ++argv;
        }
        
        // Checks if input and output are valid
        if (!input) {
            fprintf(stderr, "binconv: error: no input file specified", ** argv);
            return -1;
        }
        
        // Benchmark        
        clock_t start = clock();
        
        // Opens input file
        FILE * f = fopen(input, "rb");
        if (!f) {
            fprintf(stderr, "binconv: error: couldn't open file\n");
            return -1;
        }
        
        fseek(f, 0, SEEK_END);
        unsigned int size = ftell(f);
        if (!size) {
            fprintf(stderr, "binconv: error: file is empty!\n");
            return -1;
        }
        rewind(f);
        
        if (flags & BINCONV_FLAGS_VERBOSE) 
            printf("binconv: loaded binary\n");
        
        // Writes
        fclose(fopen(output, "w"));
        FILE * o = fopen(output, "a");
        if (!o) {
            fprintf(stderr, "binconv: error: couldn't open file\n");
            return -1;
        }
        
        fprintf(o,  lang == BINCONV_LANGS_C    ? "// generated by binconv %d.%d.%d\nunsigned char bin[%d] = { " : 
                   (lang == BINCONV_LANGS_RUST ? "// generated by binconv %d.%d.%d\nlet x:[%d] = [ " : ""), BINCONV_MAJOR, BINCONV_MINOR, BINCONV_PATCH, size);
        for (unsigned int i = 0; i < size; i++) {
            char b[8];
            fseek(f, i, SEEK_SET);
            fprintf(o, "0x%x", ftell(f));
            
            if (i < size - 1)
                fprintf(o, ", ");
            
            if (flags & BINCONV_FLAGS_VERBOSE) 
                printf("\33[2K\rbinconv: processed %d bytes", i);
        }
        if (flags & BINCONV_FLAGS_VERBOSE)
            printf("\33[2K\r");
        
        fprintf(o,  lang == BINCONV_LANGS_C    ? " };\n" : 
                   (lang == BINCONV_LANGS_RUST ? " ];\n" : ""));
        fclose(o);
        fclose(f);
        
        if (flags & BINCONV_FLAGS_VERBOSE) 
            printf("binconv: %d bytes processed in %f seconds.\n", size, ((double)clock() - start) / CLOCKS_PER_SEC);
    } else {
        printf("binconv: error: no arguments specified\n");
    }
    
    return 0;
}
